# Generated by Django 2.2 on 2022-01-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, default='', max_length=100)),
                ('instruction', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('photoURL', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
