# Generated by Django 2.2 on 2022-01-22 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photoURL',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='madeOf',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mainPhoto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modelSize',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
